apiVersion: v1
kind: Service
metadata:
  name: ai-gateway
  labels:
    app: ai-gateway
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: ai-gateway
---
apiVersion: v1
kind: Service
metadata:
  name: ai-gateway-metrics
  labels:
    app: ai-gateway
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: metrics
  selector:
    app: ai-gateway
