"""Schemas package."""

from app.schemas.admin import (
    APIKeyCreate,
    APIKeyResponse,
    ChannelCreate,
    ChannelResponse,
    ChannelTestRequest,
    ChannelTestResponse,
    ChannelUpdate,
    ModelConfigCreate,
    ModelConfigResponse,
    SubKeyCreate,
    SubKeyResponse,
    TenantCreate,
    TenantResponse,
    TenantUpdate,
)
from app.schemas.anthropic import (
    AnthropicMessage,
    AnthropicMessagesRequest,
    AnthropicResponseMessage,
    AnthropicTool,
    AnthropicUsage,
)
from app.schemas.common import (
    BaseResponse,
    ErrorDetail,
    ErrorResponse,
    HealthResponse,
    MetricsResponse,
    PaginatedResponse,
    PaginationParams,
)
from app.schemas.openai import (
    ChatCompletionChoice,
    ChatCompletionMessage,
    ChatCompletionRequest,
    ChatCompletionResponse,
    ChatCompletionStreamChoice,
    ChatCompletionStreamDelta,
    ChatCompletionStreamResponse,
    ChatCompletionTool,
    ChatCompletionToolFunction,
    Embedding,
    EmbeddingRequest,
    EmbeddingResponse,
    ModelInfo,
    ModelListResponse,
    Usage,
)

__all__ = [
    # Common
    "BaseResponse",
    "ErrorDetail",
    "ErrorResponse",
    "PaginationParams",
    "PaginatedResponse",
    "HealthResponse",
    "MetricsResponse",
    # OpenAI
    "ChatCompletionMessage",
    "ChatCompletionRequest",
    "ChatCompletionChoice",
    "ChatCompletionResponse",
    "ChatCompletionStreamDelta",
    "ChatCompletionStreamChoice",
    "ChatCompletionStreamResponse",
    "ChatCompletionTool",
    "ChatCompletionToolFunction",
    "EmbeddingRequest",
    "Embedding",
    "EmbeddingResponse",
    "Usage",
    "ModelInfo",
    "ModelListResponse",
    # Anthropic
    "AnthropicMessage",
    "AnthropicMessagesRequest",
    "AnthropicResponseMessage",
    "AnthropicTool",
    "AnthropicUsage",
    # Admin
    "TenantCreate",
    "TenantUpdate",
    "TenantResponse",
    "APIKeyCreate",
    "APIKeyResponse",
    "SubKeyCreate",
    "SubKeyResponse",
    "ChannelCreate",
    "ChannelUpdate",
    "ChannelResponse",
    "ChannelTestRequest",
    "ChannelTestResponse",
    "ModelConfigCreate",
    "ModelConfigResponse",
]
