"""Core module initialization."""

from app.core.exceptions import (
    AIGatewayError,
    AdapterError,
    AdapterRateLimitError,
    AdapterTimeoutError,
    APIKeyExpiredError,
    APIKeyNotFoundError,
    AuthenticationError,
    AuthorizationError,
    BillingError,
    ChannelNotFoundError,
    ChannelUnavailableError,
    ConfigurationError,
    MCPError,
    MCPServerNotFoundError,
    MCPToolExecutionError,
    MCPToolNotFoundError,
    ModelNotSupportedError,
    NoAvailableChannelError,
    RateLimitExceededError,
    StreamingError,
    TenantNotFoundError,
    TenantQuotaExceededError,
    ValidationError,
)
from app.core.security import (
    generate_api_key,
    generate_request_id,
    hash_api_key,
    verify_api_key_hash,
)

__all__ = [
    # Exceptions
    "AIGatewayError",
    "AuthenticationError",
    "AuthorizationError",
    "APIKeyNotFoundError",
    "APIKeyExpiredError",
    "TenantNotFoundError",
    "TenantQuotaExceededError",
    "ChannelNotFoundError",
    "ChannelUnavailableError",
    "NoAvailableChannelError",
    "RateLimitExceededError",
    "ModelNotSupportedError",
    "AdapterError",
    "AdapterTimeoutError",
    "AdapterRateLimitError",
    "StreamingError",
    "BillingError",
    "MCPError",
    "MCPToolNotFoundError",
    "MCPToolExecutionError",
    "MCPServerNotFoundError",
    "ValidationError",
    "ConfigurationError",
    # Security
    "generate_api_key",
    "hash_api_key",
    "verify_api_key_hash",
    "generate_request_id",
]
